matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode9.3
      before_install:
        - brew update && brew bundle
        - carthage checkout
        - carthage build --no-skip-current --platform ios --platform osx
      script:
        - set -o pipefail
        - xcodebuild clean test -workspace Kindness.xcworkspace -scheme 'Kindness OSX' | XCPRETTY_JSON_FILE_OUTPUT=build/kindness-osx-xcodebuild.json bundle exec xcpretty -f `bundle exec xcpretty-json-formatter`
    - os: osx
      language: objective-c
      osx_image: xcode9.3
      before_install:
        - bundle install --path ./vendor/bundle
        - brew update && brew bundle
        - carthage checkout
        - carthage build --no-skip-current --platform ios --platform osx
      script:
        - set -o pipefail
        - xcodebuild clean test -scheme 'Kindness iOS' -destination "platform=iOS Simulator,name=iPad Pro (12.9-inch) (2nd generation)" | XCPRETTY_JSON_FILE_OUTPUT=build/kindness-ios-xcodebuild.json bundle exec xcpretty -f `bundle exec xcpretty-json-formatter`
        - bundle exec danger --verbose
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      before_install:
        - git submodule update --init --recursive
        - wget -q -O - https://swift.org/keys/all-keys.asc | gpg --import -
        - wget https://swift.org/builds/swift-4.1-release/ubuntu1404/swift-4.1-RELEASE/swift-4.1-RELEASE-ubuntu14.04.tar.gz
        - tar xzf swift-4.1-RELEASE-ubuntu14.04.tar.gz
        - export PATH=${PWD}/swift-4.1-RELEASE-ubuntu14.04/usr/bin:"${PATH}"
      script:
        - swift test
